version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Kiebot@123
      MYSQL_DATABASE: hrms_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - hrms-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  employee-service:
    build:
      context: .
      dockerfile: ./apps/employee-service/Dockerfile
    container_name: employee-service
    ports:
      - "8081:8080"
    networks:
      - hrms-network
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hrms_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Kiebot@123
      NOTIFICATION_SERVICE_URL: http://notification-service:8080

  notification-service:
    build:
      context: .
      dockerfile: ./apps/notification-service/Dockerfile
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - hrms-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/notifications/health || exit 1"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  mysql-data:

networks:
  hrms-network:
    driver: bridge
